package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/swagger" // Note: v2 uses this path usually
	"github.com/shyamsundaar/karino-mock-server/controllers"
	"github.com/shyamsundaar/karino-mock-server/initializers"

	// IMPORTANT: Replace this with your actual docs path generated by 'swag init'
	_ "github.com/shyamsundaar/karino-mock-server/docs"
)

// @title Detail & Note API
// @version 1.0
// @description This is a sample CRUD API for managing Notes and Farmer Details
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email support@example.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8000
// @BasePath /api
func main() {
	app := fiber.New()
	micro := fiber.New()

	// Middleware
	app.Use(logger.New())
	app.Use(cors.New(cors.Config{
		AllowOrigins:     "http://localhost:3000",
		AllowHeaders:     "Origin, Content-Type, Accept",
		AllowMethods:     "GET, POST, PATCH, DELETE",
		AllowCredentials: true,
	}))

	// Swagger Route (Accessible at http://localhost:8000/swagger/index.html)
	app.Get("/swagger/*", swagger.HandlerDefault)

	// Mount API routes
	app.Mount("/api", micro)

	// --- Details Routes ---
	micro.Route("/details", func(router fiber.Router) {
		router.Post("/", controllers.CreateDetailHandler)
		router.Get("", controllers.FindDetails)
	})
	micro.Route("/details/:detailId", func(router fiber.Router) {
		router.Get("", controllers.FindDetailById)
		router.Patch("", controllers.UpdateDetail)
		router.Delete("", controllers.DeleteDetail)
	})

	// --- Notes Routes ---
	micro.Route("/notes", func(router fiber.Router) {
		router.Post("/", controllers.CreateDetailHandler)
		router.Get("", controllers.FindDetails)
	})
	micro.Route("/notes/:noteId", func(router fiber.Router) {
		router.Delete("", controllers.DeleteDetail)
		router.Get("", controllers.FindDetailById)
		router.Patch("", controllers.UpdateDetail)
	})

	// Health Check
	micro.Get("/healthchecker", func(c *fiber.Ctx) error {
		return c.Status(200).JSON(fiber.Map{
			"status":  "success",
			"message": "Welcome to Golang, Fiber, and GORM",
		})
	})

	log.Fatal(app.Listen(":8000"))
}

func init() {
	config, err := initializers.LoadConfig(".")
	if err != nil {
		log.Fatalln("Failed to load environment variables! \n", err.Error())
	}
	initializers.ConnectDB(&config)
}
